language: android

android:
  components:
    - build-tools-28.0.3
    - android-28

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

script: ./gradlew test
